### PR TITLE
DM-37671: add support for the photo sensor

### PR DESCRIPTION
**Pull request by r-owen**

### CODE REVIEW

**Comment by craiglagegit** [comment]
Well, I admit I don't understand how this all fits together, but I have the following comments/questions:

(1) In python/lsst/ts/atwhitelight/config_schema.py, you recommend that max_lamp_off_delay should be 4 seconds, but in  tests/data/config/_init.yaml, line 28, it is set to 2 seconds.

(2) In python/lsst/ts/atwhitelight/mock_labjack_interface.py, I think lines 56 and 60 are interchanged.

(3) I was unable to understand what happens if the lamp gets into the UNEXPECTEDLY_OFF state, i.e. the lamp failed to turn on.  In the current configuration, if the lamp doesn't turn on, I have to wait 15 minutes to try again.  What happens here?  Doe sit wait and try again, or does it FAULT?  If it faults, can I try again in a short time?

**Review by craiglagegit — APPROVED** [review]
Duplicating my comments, because I'm not sure the other comments will be visible:

Well, I admit I don't understand how this all fits together, but I have the following comments/questions:

(1) In python/lsst/ts/atwhitelight/config_schema.py, you recommend that max_lamp_off_delay should be 4 seconds, but in tests/data/config/_init.yaml, line 28, it is set to 2 seconds.

(2) In python/lsst/ts/atwhitelight/mock_labjack_interface.py, I think lines 56 and 60 are interchanged.

(3) I was unable to understand what happens if the lamp gets into the UNEXPECTEDLY_OFF state, i.e. the lamp failed to turn on. In the current configuration, if the lamp doesn't turn on, I have to wait 15 minutes to try again. What happens here? Doe sit wait and try again, or does it FAULT? If it faults, can I try again in a short time?

**Comment by r-owen** [comment]
Answers:
(1): The files data in tests/data/config are for unit tests; I want those to run reasonably fast, hence the shorter-than-recommended max_lamp_off_delay.
(2) Good catch. Fixed.
(3) UNEXPECTEDLY_OFF means the lamp failed to turn on or burned out. In both cases the CSC goes to FAULT state. But that does not turn off the cooldown timer. I'll fix that, since no light means no worries about trying again.

**Comment by r-owen** [comment]
I made additional improvements:
* Document the need for max_lamp_on_delay to be much longer (based on the KiloArc manual saying it can take up to 20 seconds to ignite the lamp).
* Handle the LAMP_UNEXPECTEDLY_OFF state much better. The lamp model will immediately try to turn off the lamp, disable the cooldown timer (no point to cooling the bulb if it is already off), and output a somewhat simpler and more logical sequence of events.

**Pull request merged**
